<?php
/**
 * PTAMesh — Export Job Cart PDF template
 * Variables available:
 * - $ptx_job_id
 * - $ptx_items
 * - $ptx_labor
 */
if (!defined('ABSPATH')) { exit; }

// Basic headers for HTML download (the class sets these before include if needed)
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Job Cart #<?php echo intval($ptx_job_id); ?></title>
  <style>
    body { font-family: Arial, sans-serif; color: #222; }
    h1, h2 { margin: 0.2em 0; }
    .section { margin: 1em 0; }
    table { width: 100%; border-collapse: collapse; margin-top: 0.5em; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    th { background: #f7f7f7; }
    .footer { margin-top: 2em; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <h1>Job Cart #<?php echo intval($ptx_job_id); ?></h1>

  <div class="section">
    <h2>Materials</h2>
    <table>
      <thead>
        <tr>
          <th>Description</th>
          <th>Qty</th>
          <th>Unit</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
        <?php
        foreach ($ptx_items as $row) {
          $desc = isset($row['product_id']) ? esc_html((string)$row['product_id']) : 'Unknown';
          $qty  = isset($row['qty']) ? intval($row['qty']) : 0;
          $unit = isset($row['unit_price']) ? floatval($row['unit_price']) : 0.0;
          $total = round($unit * $qty, 2);
          echo '<tr>';
          echo '<td>'.$desc.'</td>';
          echo '<td>'.$qty.'</td>';
          echo '<td>'.$unit.'</td>';
          echo '<td>'.$total.'</td>';
          echo '</tr>';
        }
        ?>
      </tbody>
    </table>
  </div>

  <div class="section">
    <h2>Labor</h2>
    <table>
      <thead>
        <tr>
          <th>Technician</th>
          <th>Hours</th>
          <th>Rate</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
        <?php
        foreach ($ptx_labor as $row) {
          $tech  = isset($row['tech']) ? esc_html((string)$row['tech']) : 'Technician';
          $hours = isset($row['hours']) ? floatval($row['hours']) : 0.0;
          $rate  = isset($row['rate']) ? floatval($row['rate']) : 0.0;
          $total = round($hours * $rate, 2);
          echo '<tr>';
          echo '<td>'.$tech.'</td>';
          echo '<td>'.$hours.'</td>';
          echo '<td>'.$rate.'</td>';
          echo '<td>'.$total.'</td>';
          echo '</tr>';
        }
        ?>
      </tbody>
    </table>
  </div>

  <p class="footer">Generated by PTAMesh — Job carts, pricing, receiving, and exports.</p>
</body>
</html>